# Log4J2 Configuration

# Root Logger
status=warn
name=CompositeLogging

# Appenders
appender.stdout.type=Console
appender.stdout.name=stdout
appender.stdout.target=SYSTEM_OUT
appender.stdout.layout.type=PatternLayout
appender.stdout.layout.pattern=%m%n

appender.fout.type=File
appender.fout.name=fout
appender.fout.fileName=log/composite.log
appender.fout.layout.type=PatternLayout
appender.fout.layout.pattern=%p\t%d{ISO8601}\t%r\t%c\t[%t]\t%m%n

# Root Logger Configuration
rootLogger.level=info
rootLogger.appenderRefs=stdout,fout
rootLogger.appenderRef.stdout.ref=stdout
rootLogger.appenderRef.fout.ref=fout